# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('good_name', models.CharField(max_length=254, unique=True)),
                ('good_count', models.IntegerField()),
                ('good_cost', models.IntegerField()),
                ('good_characteristic', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Good',
                'verbose_name_plural': 'Goods',
            },
        ),
    ]
