# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horses_Model',
            fields=[
                ('horse_id', models.AutoField(primary_key=True, serialize=False)),
                ('horse_name', models.CharField(max_length=100)),
            ],
        ),
    ]
