# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_horses_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('runs_date', models.DateField()),
                ('runs_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_run_id', models.IntegerField()),
                ('runs_horse_id', models.CharField(max_length=100)),
            ],
        ),
    ]
