# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_run_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runs_model',
            fields=[
                ('smth', models.AutoField(primary_key=True, serialize=False)),
                ('runs_run_id', models.IntegerField()),
                ('runs_horse_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Run',
            new_name='Run_model',
        ),
        migrations.DeleteModel(
            name='Runs',
        ),
    ]
