# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20171207_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horses_Model',
            new_name='Horses',
        ),
        migrations.RenameModel(
            old_name='Run_model',
            new_name='Run',
        ),
        migrations.RenameModel(
            old_name='Runs_model',
            new_name='Runs',
        ),
    ]
